### PR TITLE
add largestProductOfThree method

### PR DESCRIPTION
**Pull request by RayenRaffa**
Hey aboubakr, thank you very much for your feedback on the previous toy problems ! 
I really appreciate that man :)

### CODE REVIEW

**Comment by RayenRaffa** [comment]
add urlQueryString method

**Comment by RayenRaffa** [comment]
check balanced parentheses in string

**Comment by RayenRaffa** [comment]
Add shuffle deck method

**Comment by AbobkerElaghel** [comment]
a rather impressive work mate, keep it up!!

**Pull request merged**
